config/routes.rb
Rails.application.routes.draw do
  get "/tasks", to: "tasks#index"
  get "/tasks/:id", to: "tasks#show", as: :task
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task1 = Task.first
  end

  def show
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="margin-top: 30px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul style="list-style-type: none">
  <% @tasks.each do |task| %>
    <li>
      <input type="checkbox"
        <%= "checked" if task.completed %>
      />
      <%= link_to task.title, task_path(id: task.id) %>
    </li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<div class="alert alert-success" role="alert">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
</div>
<p>
  <input type="checkbox" <%= "checked" if @task.completed %> />
  This task is
  <%=
    if @task.completed
      "completed"
    else
      "not completed yet"
    end
  %>
</p>
<hr>
<p><%= link_to "Back to list", tasks_path %></p>